### ISSUE TITLE
Problem with wifiphiser

### ISSUE THREAD

**Issue by HackThisJack** [keralahacker/tp-link-v3-usb#5]
Hello when start wifiphiser receve this

*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-09-10 13:10
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 1070, in devinfo
    rmsg = nl.nl_recvmsg(nlsock)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg
    msg = nlmsg_fromstream(sock.recv())
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
    raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 408, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/opmode.py", line 54, in initialize
    interfaces.is_add_vif_required(args.interface, 
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 813, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 277, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 2279, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 278, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 1083, in devinfo
    raise pyric.error(pyric.EPROTONOSUPPORT, "Device does not support nl80211")
pyric.error: [Errno 93] Device does not support nl80211

any solution???

**Comment by keralahacker** [comment]
- sudo apt update
- sudo apt dist-upgrade
- reboot
- sudo apt install linux-headers-$(uname -r)

reboot your system 
 the above command is a first-time installation step 
 after that,  use this for wifiphiser

- sudo rmmod r8188eu.ko
- sudo modprobe 8188eu

Disconnect the device and connect again.. for each and every time you use the adapter
